import junit.framework.*;
/*
 * RootSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class RootSuite extends TestCase {
    
    public RootSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("RootSuite");
        suite.addTest(com.ComSuite.suite());
        return suite;
    }
    
}
