package com.abbt.timesheet.services;
import junit.framework.*;
/*
 * ServicesSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class ServicesSuite extends TestCase {
    
    public ServicesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ServicesSuite");
        suite.addTest(com.abbt.timesheet.services.TimesheetServiceTest.suite());
        suite.addTest(com.abbt.timesheet.services.TimesheetServiceImplTest.suite());
        suite.addTest(com.abbt.timesheet.services.ServiceFactoryTest.suite());
        return suite;
    }
    
}
