package com.abbt.timesheet.entities;
import junit.framework.*;
/*
 * EntitiesSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:14 PM
 */

/**
 *
 * @author shannan
 */
public class EntitiesSuite extends TestCase {
    
    public EntitiesSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("EntitiesSuite");
        suite.addTest(com.abbt.timesheet.entities.TimesheetDetailTest.suite());
        suite.addTest(com.abbt.timesheet.entities.UserTest.suite());
        suite.addTest(com.abbt.timesheet.entities.KeyValueTest.suite());
        suite.addTest(com.abbt.timesheet.entities.UserCompanyTest.suite());
        suite.addTest(com.abbt.timesheet.entities.CompanyTest.suite());
        suite.addTest(com.abbt.timesheet.entities.AddressTest.suite());
        suite.addTest(com.abbt.timesheet.entities.TimesheetTest.suite());
        suite.addTest(com.abbt.timesheet.entities.TimesheetStatusHistoryTest.suite());
        suite.addTest(com.abbt.timesheet.entities.TimesheetStatusTest.suite());
        return suite;
    }
    
}
