package com.abbt.timesheet.daos;
import junit.framework.*;
/*
 * DaosSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class DaosSuite extends TestCase {
    
    public DaosSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("DaosSuite");
        suite.addTest(com.abbt.timesheet.daos.TimesheetDBDaoTest.suite());
        suite.addTest(com.abbt.timesheet.daos.TimesheetDBDaoImplTest.suite());
        return suite;
    }
    
}
