package com.abbt;
import junit.framework.*;
/*
 * AbbtSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class AbbtSuite extends TestCase {
    
    public AbbtSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("AbbtSuite");
        suite.addTest(com.abbt.timesheet.TimesheetSuite.suite());
        return suite;
    }
    
}
