package com.abbt.timesheet.portlets;
import junit.framework.*;
/*
 * PortletsSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:14 PM
 */

/**
 *
 * @author shannan
 */
public class PortletsSuite extends TestCase {
    
    public PortletsSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("PortletsSuite");
        suite.addTest(com.abbt.timesheet.portlets.RecentTimesheetsTest.suite());
        return suite;
    }
    
}
