package com.abbt.timesheet;
import junit.framework.*;
/*
 * TimesheetSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class TimesheetSuite extends TestCase {
    
    public TimesheetSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("TimesheetSuite");
        suite.addTest(com.abbt.timesheet.portlets.PortletsSuite.suite());
        suite.addTest(com.abbt.timesheet.entities.EntitiesSuite.suite());
        suite.addTest(com.abbt.timesheet.services.ServicesSuite.suite());
        suite.addTest(com.abbt.timesheet.daos.DaosSuite.suite());
        return suite;
    }
    
}
