/*
 * ServicesSuite.java
 * JUnit based test
 *
 * Created on April 2, 2007, 8:50 PM
 */

package com.abbt.crm.services;

import junit.framework.*;

/**
 *
 * @author shannan
 */
public class ServicesSuite extends TestCase {
    
    public ServicesSuite(String testName) {
        super(testName);
    }            

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ServicesSuite");
        suite.addTest(com.abbt.crm.services.EmployeeServiceImplTest.suite());
        return suite;
    }
    
}
