package com;
import junit.framework.*;
/*
 * ComSuite.java
 * JUnit based test
 *
 * Created on May 3, 2007, 11:15 PM
 */

/**
 *
 * @author shannan
 */
public class ComSuite extends TestCase {
    
    public ComSuite(String testName) {
        super(testName);
    }

    protected void setUp() throws Exception {
    }

    protected void tearDown() throws Exception {
    }

    /**
     * suite method automatically generated by JUnit module
     */
    public static Test suite() {
        TestSuite suite = new TestSuite("ComSuite");
        suite.addTest(com.abbt.AbbtSuite.suite());
        return suite;
    }
    
}
